### PR TITLE
feat: add ability to evoke a function on Deploy of Surface from faDeploy attr

### PR DESCRIPTION
**Pull request by steveblue**
Sometimes the $famous find service doesn't work when referencing classes that are created dynamically. This creates a problem, because then you can't do something on 'deploy' of a RenderNode. Adding the ability to call a function on the local scope from an attribute on the Surface after it is deployed solves this problem, is minimally invasive and the implementation is actually pretty streamlined.  

From faSurface:
```
            if(attrs.faDeploy){
              isolate.renderNode.on("deploy",function(){
                var fn = scope[attrs.faDeploy];
                if(typeof fn === 'function') {
                  fn(attrs.faDeploy)();
                }
              });
            }
```

In a template you can reference the function via a string:

```

fa-deploy="deployFunction"

```

And now in a custom directive or controller, you can call a function on the local scope after the Surface is deployed.

```
         scope.deployFunction = function(){

              return function(){
                console.log('do something on the local scope');
              };

          };
```

### CODE REVIEW

**Comment by jordanpapaleo** [comment]
Hey Steve -  Thanks for putting this together.  It looks good.  Quick question, when was the last time you updated your fork from master?  My fa-surface has 100 more lines than yours?

Thanks,

Jordan

**Comment by steveblue** [comment]
Whoops, I thought I had updated from the latest master. Do you want me to resubmit?

**Comment by jordanpapaleo** [comment]
That would be great.

**Comment by steveblue** [comment]
Are there any other RenderNodes that might benefit from this treatment? I could do a pass...

**Comment by jordanpapaleo** [comment]
Not sure.  I am still playing catchup with my familiarity in this repo (as if its not obvious ;) )  I'll check with @zackbrown.  

I also want to say how much we appreciate your contributions to the codebase as well as stepping up and providing support in the issues.

**Comment by steveblue** [comment]
I pushed an updated version to f-deploy-attribute with the latest commit being a merge from master.

**Comment by jordanpapaleo** [comment]
Thanks Steve!

**Pull request merged**
