### PR TITLE
fix make animate return a promise

### LINKED ISSUE #340: Animate addClass/removeClass/setClass don't return promises.
In commit 132c4ce2782ae1d0dc53c13de7ea2cb5723f39c9 $animate was updated to return a promise for 'enter', 'leave', and 'move'. Unfortunately, this commit didn't make $animate return a promise for addClass/removeClass/setClass.

### PR DESCRIPTION
**Pull request by jamesgroat**
Fixes #340 by capturing the promise and returning it.

### CODE REVIEW

**Comment by jamesgroat** [comment]
Extra commit/merge on this pr is to clean up accidental changes to whitespace. The end result looks correct to me.

**Comment by zackbrown** [comment]
Hi @jamesgroat — thank you for putting this PR together and for fixing this issue with promises.  It looks like you haven't signed our CLA—before we can merge this, can you please sign the CLA [here](http://famo.us/cla/)?

**Comment by jamesgroat** [comment]
Done.

**Comment by zackbrown** [comment]
Great, thank you!

**Pull request merged**
